cmd/fdsn-ws/fdsn_event.go
cmd/fdsn-ws/fdsn_station.go

The first commit is gofmt for fdsn_event.go.

Time handling

---

cmd/fdsn-ws/fdsn_station.go
cmd/fdsn-ws/fdsn_station_test.go
cmd/fdsn-ws/routes_test.go
vendor/github.com/StefanSchroeder/Golang-Ellipsoid/LICENSE
vendor/github.com/StefanSchroeder/Golang-Ellipsoid/ellipsoid/ellipsoid.go
vendor/vendor.json

The lat-lon query for event service (#51) should use db function so not in this PR.

Add lat/lon radius query for station as requested in #50.

---

cmd/fdsn-ws/assets/fdsn-ws-event.wadl

Not sure if we should put IncludeAllOrigins, IncludeAllMagnitudes, and IncludeArrivals so I've skipped them.

Update event application.wadl.

---

cmd/fdsn-ws-nrt/assets/tmpl/fdsn-ws-dataselect.wadl
cmd/fdsn-ws-nrt/env.list
cmd/fdsn-ws-nrt/fdsn_dataselect.go
cmd/fdsn-ws/assets/tmpl/fdsn-ws-dataselect.wadl
cmd/fdsn-ws/assets/tmpl/fdsn-ws-event.wadl
cmd/fdsn-ws/assets/tmpl/fdsn-ws-station.wadl
cmd/fdsn-ws/env.list
cmd/fdsn-ws/fdsn_dataselect.go
cmd/fdsn-ws/fdsn_event.go
cmd/fdsn-ws/fdsn_event_test.go
cmd/fdsn-ws/fdsn_station.go
internal/fdsn/dataselect.go
internal/fdsn/dataselect_test.go

Proper base url for wadl output.

Added "nodata" and "updatedafter" query parameter.

---

cmd/fdsn-ws/fdsn_event.go
cmd/fdsn-ws/fdsn_event_test.go
cmd/fdsn-ws/fdsn_station.go
cmd/fdsn-ws/server_test.go

Add abbreviation support for event service. Fix longitude cross 180 degree problem while querying with maxlon or minion.

---

cmd/fdsn-ws/data_holdings.go
cmd/fdsn-ws/fdsn_dataselect.go

This might affect the performance since we have to check more miniSEED records but there doesn't seem to be much choice.

Extend search range for dataselect as requested in #78.

---

cmd/fdsn-holdings-consumer/data_holdings.go
cmd/fdsn-holdings-consumer/data_holdings_test.go
cmd/fdsn-holdings-consumer/main.go

Improve the fdsn-holdings-consumer db performance with a
prepared statement and on conflict retry (replaces transaction).

fdsn-holdings-consumer

---

cmd/fdsn-ws/assets/tmpl/fdsn-ws-dataselect.wadl
cmd/fdsn-ws/assets/tmpl/fdsn-ws-station.wadl
cmd/fdsn-ws/fdsn_event.go
cmd/fdsn-ws/fdsn_event_test.go
cmd/fdsn-ws/fdsn_station.go

At this moment we don't provide EventLocation for text format event service.

Format parm

---

cmd/fdsn-ws/data_holdings.go
cmd/fdsn-ws/data_holdings_test.go
cmd/fdsn-ws/fdsn_dataselect.go
cmd/fdsn-ws/routes.go
cmd/fdsn-ws/routes_test.go

Add a service for retrieving data metrics.

Service for data metrics

---

cmd/fdsn-ws/fdsn_station.go

* use the sensor type as the sensor description e.g., Short Period Seismometer
* fix fmt error for pointer to float64 in csv output

station CSV output changes

---

cmd/fdsn-ws/fdsn_station.go
cmd/fdsn-ws/fdsn_station_test.go

Should fulfil https://github.com/GeoNet/tickets/issues/1710.
The parameter validating looks clumsy but it seems the only way I can think.

Add startbefore,startafter,endbefore,endafter

---

cmd/fdsn-ws/fdsn_station.go
cmd/fdsn-ws/fdsn_station_test.go

As the conclusion in #140:
* Include a station if its end time is after the "startTime" query parameter.
* Include a station if its start time is before the "endTime" query parameter.

Fix query start/end time as discussed in #140.

---

cmd/fdsn-ws/fdsn_station_test.go
cmd/fdsn-ws/routes_test.go

Added more tests.
Now most happy paths in this project have proper test coverage.

More tests

---

.gitignore
cmd/fdsn-quake-consumer/sc3ml_backload_test.go

Add an integration test that can be used to bulk load SC3ML from the
local filesystem into the FSDN database.

Add a test for bulkloading SC3ML to the FDSN database

---

cmd/fdsn-ws/fdsn_station.go
cmd/fdsn-ws/fdsn_station_test.go
vendor/github.com/GeoNet/kit/weft/handlers.go
vendor/github.com/GeoNet/kit/weft/weft.go
vendor/github.com/GeoNet/kit/weft/wefttest/wefttest.go
vendor/vendor.json

Station service didn't recognise _format=text_ in post.

Fix station post text format.

---

cmd/fdsn-ws/fdsn_dataselect.go

Log the number of files and the time window that will be used
to fill a response.
Resolves https://github.com/GeoNet/tickets/issues/3119

Add logging of response

---

vendor/github.com/GeoNet/kit/weft/assets.go
vendor/github.com/GeoNet/kit/weft/handlers.go
vendor/vendor.json

Similar to PRs on other web services but fdsn doesn't have any subResources so don't need the weft AssetHandler.

Weft Update

---

cmd/fdsn-ws-nrt/fdsn_dataselect.go
cmd/fdsn-ws-nrt/log.go
cmd/fdsn-ws/fdsn_dataselect.go
cmd/fdsn-ws/fdsn_station.go
cmd/fdsn-ws/log.go
vendor/github.com/GeoNet/kit/weft/handlers.go
vendor/github.com/GeoNet/kit/weft/weft.go
vendor/vendor.json

Enable request logging. Fix a bug in stations service.

---

cmd/fdsn-slink-db/main.go

Changed SLINK settings to cooperate with recent platform change.

Updated SLINK settings

---

.travis.yml

https://github.com/GeoNet/tickets/issues/6242

add slack notification on build failure

---

build.sh
cmd/fdsn-quake-consumer/Dockerfile

just wonder could update `quay.io/geonet/alpine:3.9` to `quay.io/geonet/alpine:3.10`

update geonet docker image

---

README.md
fdsn-batch-test.sh
fdsn-test-urls.txt

Fix test script errors.

---

.gitignore
.travis.yml
Dockerfile.cgo
Dockerfile.tmplate
build.sh
cmd/fdsn-quake-consumer/Dockerfile

- fix cgo compile
- update to geonet `go-scratch` image

fix cgo build issue

---

cmd/fdsn-ws/fdsn_dataselect.go

As title. This will fix https://github.com/GeoNet/tickets/issues/10207

Better http status code for dataselet query errors.

---

cmd/fdsn-quake-consumer/assets/sc3ml_0.10__quakeml_1.2.xsl
cmd/fdsn-quake-consumer/assets/sc3ml_0.11__quakeml_1.2.xsl
cmd/fdsn-quake-consumer/assets/sc3ml_0.7__quakeml_1.2.xsl
cmd/fdsn-quake-consumer/assets/sc3ml_0.8__quakeml_1.2.xsl
cmd/fdsn-quake-consumer/assets/sc3ml_0.9__quakeml_1.2.xsl
cmd/fdsn-quake-consumer/sc3ml_test.go

As requested in https://github.com/GeoNet/help/issues/105 and https://github.com/GeoNet/tickets/issues/12889.

Update xsl files.

---

cmd/fdsn-ws/routes.go

As described in https://github.com/GeoNet/tickets/issues/16074

fix: no message body reponsed when the query returns no content

---

cmd/fdsn-ws/fdsn_dataselect.go

Ticket https://github.com/GeoNet/tickets/issues/15054
Fix fdsn_dataselect error when no data exist for specified key

fix dataselect query no content issue

---

cmd/fdsn-ws/assets/robots.txt
cmd/fdsn-ws/routes.go

Add robots handler for crawlers

feat: add robots.txt handler
