GeoNet/fdsn

cmd/fdsn-ws/fdsn_station.go, cmd/fdsn-ws/fdsn_station_test.go, cmd/fdsn-ws/routes_test.go
Fix - The units of maxradius and minradius are degree
Fix - maxradius and minradius have default value.
@nbalfour 
To find the difference of 2 points in degrees: we first get the distance of 2 points in the unit of km,  then divide it with 111 to get the degrees. Is this OK for you?
=> FDSN station radius filter as requested in #50.

cmd/fdsn-ws-nrt/data_nrt.go, cmd/fdsn-ws-nrt/data_nrt_test.go, cmd/fdsn-ws-nrt/env.list, cmd/fdsn-ws-nrt/fdsn_dataselect.go, cmd/fdsn-ws-nrt/server.go
Improve the use of the RAM cache for miniSEED records:
* back fill the cache on start up.
* actively fill the cache going forwards.
I've added the env var CACHE_SIZE to prod already so this can merge anytime.
=> Improve cache usage.

cmd/fdsn-ws-nrt/data_nrt.go, cmd/fdsn-ws-nrt/server.go
Now only prime cache for small time chunks.  There is no large
backfilling.  Remove the record count limit on the cache priming.
=> Simplify cache priming

cmd/fdsn-slink-db/app.go, cmd/fdsn-ws-nrt/data_nrt_test.go, internal/holdings/holdings.go, vendor/github.com/GeoNet/kit/mseed/msrecord.go, vendor/vendor.json
As requested in #67 .
The old mseed library returns strings with null terminated so we'll have to post processing them. Now the library has been fixed.
=> Remove unnecessary trailing null trimming after mseed lib updated.

.travis.yml, build.sh, cmd/fdsn-slink-db/app.go, cmd/fdsn-ws-nrt/routes.go, cmd/fdsn-ws/routes.go
Improve the soh routes in fdsn-ws and fdsn-ws-nrt.  They now check
for data in the appropriate table.  This give some indication that the
service is functioning as required.
Resolves #105
Resolves #103
=> Improve soh routes for external probes

cmd/fdsn-ws-nrt/fdsn_dataselect.go
#117
Ensure that dataselect follows the FDSN standard by returning a 204 (or a 404 if specified) when no data is found for the requested query.
=> Fix for issue #117

cmd/fdsn-ws-nrt/routes.go, cmd/fdsn-ws-nrt/routes_test.go, cmd/fdsn-ws/routes.go, cmd/fdsn-ws/routes_test.go
Simpler SOH probes.  The previous versions cause a lot of DB load.
These just check if the DB can be used.
=> soh probes

cmd/fdsn-ws-nrt/fdsn_dataselect.go, cmd/fdsn-ws/fdsn_dataselect.go, cmd/fdsn-ws/fdsn_station.go, internal/fdsn/dataselect.go, internal/fdsn/dataselect_test.go
For ticket https://github.com/GeoNet/tickets/issues/1728.
FDSN's spec allows ALL ASCII CHARS as query parameter for network,station,channel, and location. And only "*" and "?" has special meanings so all other chars is allowed but they'll be quoted with backslash if they are part of regex meta chars.
SQL injection check:
In fdsn repo, all database queries are using parameterised db.Query() or db.Exec() so should be safe from SQL injection. (Except sc3ml is combining values() string but it's only taking integer values)
=> Fix station/dataselect query parameter

build.sh
Required as part of AWS SQS, CA updates.
Changes proposed in this pull request:
- Modify build scripts to source required container resources (CA certificates and tzdata) from a separate container (`alpine:3.7`).
The following production changes are required to deploy these changes:
- Rebuild and deploy:
- fdsn-quake-consumer
- fdsn-holdings-consumer
Check the box that applies to this code review.  If necessary please seek help with adding a checklist guide for the reviewer.
When assigning the code review please consider the expertise needed to review the changes.
=> Gather the CA certificates and zoneinfo resources from alpine:3.7

cmd/fdsn-ws/assets/fdsn-ws-dataselect.html, cmd/fdsn-ws/fdsn_dataselect.go
Related to https://github.com/GeoNet/tickets/issues/3759
This PR restricts Dataselect queries to either 60 days (more specifically day files) (2 months) OR a maximum of 30 minutes. 
This implementation assumes it is ok to request those 60 days in any combination (e.g. 2days of each channel across 30 channels OR 60 days of 1 channel). i.e. as long as: 
```
[num of channels] * [num of days OR partial days] <= 60 OR longest request <= 30mins
```
The request will be allowed.
It does not change limits on the other queries (event or station). 
Data metrics are limited to maximum files of 60 but have no 30minute 'grace' window in this implementation.
=> Limit Dataselect Queries

cmd/fdsn-ws/fdsn_station.go
Resolves #GeoNet/tickets/issues/4793
Changes proposed in this pull request:
-  apply time filter on `channel` for `level==response`
The following production changes are required to deploy these changes:
- None
Check the box that applies to this code review.  If necessary please seek help with adding a checklist guide for the reviewer.
When assigning the code review please consider the expertise needed to review the changes.
*Insert check list here if needed.*
=> apply time filter on channel for level response

cmd/fdsn-ws-nrt/fdsn_dataselect.go, cmd/fdsn-ws-nrt/routes_test.go, cmd/fdsn-ws/fdsn_dataselect.go, cmd/fdsn-ws/routes_test.go, internal/fdsn/dataselect.go, internal/fdsn/dataselect_test.go
Reject unreasonable query parameters for `network`, `station`, `location`, and `channel` parameter - that means we're rejecting regex query parameters and only allowing `*`, `?`, `--` .
Previously we accept those parameters and returns with 204 (empty result).
=> Filter channels parameter.

internal/fdsn/dataselect.go, internal/fdsn/dataselect_test.go
As stated in https://github.com/GeoNet/fdsn/issues/199.
This fix affects `fdsn-ws` and `fdsn-ws-nrt`.
=> Fix comma seperated parameters filtered incorrectly.

README.md, fdsn-batch-test.sh, fdsn-test-urls.txt, internal/fdsn/dataselect.go, internal/fdsn/dataselect_test.go
Fixed a parameter error:
A query like `/fdsnws/dataselect/1/query?network=NZ&sta=WEL&location=--,10&starttime=2018-05-15T23:45:00&endtime=2018-05-15T23:45:10` should get at least the location 10 but got nothing.
Also in this PR I implemented the script tool to load URLs specified in  https://github.com/GeoNet/tickets/issues/7524 and test against FDSN services.
=> Fix parameter error and test tool

README.md, fdsn-batch-test.sh, fdsn-test-urls.txt
Made some change to test scripts to make it better and able to test staging servers.
Enabled the "TODO" urls (will fail against existing deployment of FDSN and FDSN-NRT, should pass after the service updated).
=> Update test script to test against any FDSN test service.

.gitignore, Dockerfile_template, build.sh
As title.
Previous docker improvement made all app running in container having `app` as the executable name, this unable to distinguish the real application in Datadog metrics.
=> Fix docker build app name issue so metrics in Datadog got their real app name.

cmd/fdsn-ws/env.list, cmd/fdsn-ws/fdsn_dataselect.go, cmd/fdsn-ws/server.go
Today there have been some POST requests to FDSN that have resulted in out of memory issues. At the moment we can't see what parameters are being provided in those POST requests, so this just logs them just before they're executed.
=> Log POST body when needed

fdsn-test-urls.txt
The original URL might return no data, so added another station as suggested by Jerome.
=> Change test sample url.

cmd/fdsn-ws/fdsn_event.go, cmd/fdsn-ws/fdsn_event_test.go
As stated in https://github.com/GeoNet/fdsn/issues/212.
Below are results to query against 2 points on the different side of meridian.
The existing query
```
fdsn=> select ST_X(origin_geom::GEOMETRY),ST_Y(origin_geom::GEOMETRY), ST_Distance(origin_geom::GEOMETRY, ST_SetSRID(ST_Makepoint(-179.40,-40.57), 4326)) from fdsn.event;
st_x     |     st_y     |    st_distance
--------------+--------------+--------------------
176.3257242 | -40.57806609 |  355.7257242914494
-176.3257242 | -40.57806609 | 3.0742863816296597
(2 rows)
```
As you can see the above results, the distance between -179.40 to 176.32 is 355.
Below is the result of updated SQL query:
```
fdsn=> select ST_X(origin_geom::GEOMETRY),ST_Y(origin_geom::GEOMETRY), ST_Distance(ST_ShiftLongitude(origin_geom::GEOMETRY), …
```
=> Fix query cross 180 meridian issue for event service.

cmd/fdsn-ws/assets/tmpl/fdsn-ws-event.wadl, cmd/fdsn-ws/assets/tmpl/fdsn-ws-station.wadl, cmd/fdsn-ws/fdsn_dataselect.go, cmd/fdsn-ws/fdsn_event.go, cmd/fdsn-ws/fdsn_event_test.go, cmd/fdsn-ws/fdsn_station.go, cmd/fdsn-ws/routes.go, cmd/fdsn-ws/server.go, internal/fdsn/dataselect.go, internal/fdsn/dataselect_test.go
Regarding to https://github.com/GeoNet/tickets/issues/10574.
Added `EventType` column for compliance with FDSN event service v1.2.
The stations service has some unsupported query parameters like event service, but I'm not changing it to use a generalised error message because some services really using that query parameter - though the value is always the default value and requires no operation for existing query.
=> Add EventType column for v1.2 in /event service.

cmd/fdsn-ws/fdsn_station.go, cmd/fdsn-ws/fdsn_station_test.go
As requested in https://github.com/GeoNet/tickets/issues/12671.
Also, text output will be in sync with XML output https://github.com/GeoNet/help/issues/103.
Previously we deliberately make it not exists, so the fix is remove those extras.
=> Fix station filter logic for nodes having no children.

cmd/fdsn-ws/fdsn_station.go
As described in https://github.com/GeoNet/fdsn/issues/233.
Stations service with level=channel, should be 16 columns result, even there's no such channel. This fixes it.
Deployed in dev and ran test `haz` locally, works well.
Checked source code of ShakingLayer, StrongMotion(lasso), www-geonet. All not affected by this bug.
=> Fix station service text output bug.

.github/workflows/build.yml, Dockerfile.tmplate, cmd/fdsn-quake-consumer/Dockerfile, etc/scripts/initdb.sh
changes include:
- add workflow for Docker build, per app in ./cmd with push to ECR
- go apps for Go validations
depends on https://github.com/GeoNet/terraform-aws/pull/847, https://github.com/GeoNet/Actions/pull/112, https://github.com/GeoNet/Actions/pull/116
should should be viewed as an example of an intermediary step between current things and Go 1.20 and ko
=> feat: use GH Actions and separate Dockerfiles

cmd/fdsn-ws/fdsn_station.go
As described in https://github.com/GeoNet/tickets/issues/14280.
Station SMHS LFF has empty InstrumentSensitivity data. This code makes the field output empty like this:
```
#Network | Station | Location | Channel | Latitude | Longitude | Elevation | Depth | Azimuth | Dip | SensorDescription | Scale | ScaleFreq | ScaleUnits | SampleRate | StartTime | EndTime
NZ|SMHS|50|LFF|-43.262160|172.334630|181.000000|0.000000|0.000000|0.000000|Fluxgate Magnetometer||||1.000000|2012-10-16T04:30:00|2013-01-15T11:00:00
NZ|SMHS|50|LFF|-43.262160|172.334630|181.000000|0.000000|0.000000|0.000000|Fluxgate Magnetometer||||1.000000|2013-01-16T00:30:00|2013-04-18T00:00:00
NZ|SMHS|50|LFF|-43.262160|172.334630|181.000000|0.000000|0.000000|0.000000|Fluxgate …
```
=> Fix station bug for empty InstrumentSensitivity responses.

cmd/fdsn-ws/routes.go, cmd/fdsn-ws/routes_test.go
As requested in https://github.com/GeoNet/tickets/issues/15492
For reviewer: Golang's `mux` auto adds `/path` when the handler pattern is `/path/`. (This means specifying `/path/` makes both `/path` and `/path/` work)
=> chore: allows slash at the end of each query method

cmd/fdsn-ws/fdsn_dataselect.go
As requested in https://github.com/GeoNet/tickets/issues/16563.
Unable to add test cases due to complexity to prepare test data.
=> feat: add IU/SNZO for querie special case

cmd/fdsn-ws/fdsn_dataselect.go
Regarding https://github.com/GeoNet/tickets/issues/16563.
Previous fix was incorrect due to the pattern string has already changed to regex first so should use regex as comparison. The logic remains the same (only allows IU/SNZO to pass)
=> fix: incorrect checking for IU/SNZO

cmd/fdsn-holdings-consumer/main.go, cmd/fdsn-quake-consumer/main.go, cmd/fdsn-ws/fdsn_dataselect.go, cmd/fdsn-ws/server.go, go.mod, go.sum, vendor/github.com/GeoNet/kit/aws/s3/s3.go, vendor/github.com/GeoNet/kit/aws/sqs/sqs.go, vendor/github.com/GeoNet/kit/health/check.go, vendor/github.com/GeoNet/kit/health/service.go, vendor/github.com/GeoNet/kit/seis/ms/doc.go, vendor/github.com/GeoNet/kit/seis/ms/header.go, vendor/github.com/GeoNet/kit/seis/ms/record.go, vendor/github.com/GeoNet/kit/seis/ms/steim.go, vendor/github.com/GeoNet/kit/slogger/logger.go, vendor/github.com/GeoNet/kit/weft/weft.go, vendor/modules.txt
Ticket https://github.com/GeoNet/tickets/issues/13878
Add health check for services
=> feat: add health checks

cmd/fdsn-ws/fdsn_dataselect.go
Ticket https://github.com/GeoNet/tickets/issues/15054
Fix fdsn_dataselect error when no data exist for specified key (single station/channel)
=> fix dataselect query no content issue 

cmd/fdsn-quake-consumer/sc3ml_test.go, cmd/fdsn-ws/fdsn_event_test.go, cmd/fdsn-ws/routes_test.go, cmd/fdsn-ws/server_test.go, internal/fdsn/dataselect.go
Ticket https://github.com/GeoNet/tickets/issues/17374
Update event type in validation and add tests for new event types
Deployed on dev, try
```
curl -X GET -I "http://tf-dev-fdsn-web-1308277073.ap-southeast-2.elb.amazonaws.com/fdsnws/event/1/query?starttime=2022-01-01T00:00:00&endtime=2025-04-28T22:00:00&format=text&eventtype=volcano-tectonic"
```
=> update event types
